version: '2'
services:
  mount-rclone01:
    image: mumiehub/rclone-mount:latest
#    privileged: true
    cap_add:
    - SYS_ADMIN
    devices:
    - /dev/fuse
    security_opt:
    - apparmor:unconfined
    environment:
      RemotePath: 'mediaefs:'
      MountCommands: --allow-other --uid 1000 --gid 1000 --umask 002 --dir-cache-time 1000h --poll-interval 15s --vfs-read-chunk-size 32M
    stdin_open: true
    tty: true
    volumes:
    - /path/to/config:/config
    - shared_volume:/mnt/mediaefs:shared
